# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11166874a76e7183f8d7df2d1b89e8c39adbd145916b6ecf539174ba84d1333fcf882d13c1e833e6d55a13fe2ec3ff63863e2812aedb12cda9a987e8220eb51b

test:
  secret_key_base: e6c29dff085304c73a96cc097703257ec32e300dc06241a446b220f81c0d1686803ccba9250eaa9742132afb89af1756c7c17edb3d1f97106f19df9d504b425c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
